# Generated by Django 4.1.2 on 2022-10-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
