# Generated by Django 4.1.2 on 2022-10-27 08:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_alter_uploadfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
