# Generated by Django 4.1.2 on 2022-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_contact_category_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
